version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    restart: 'unless-stopped'
    networks:
      - backend
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Click@123
    networks:
      - backend
    volumes:
      - mongodbdata:/data/db

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
  mongodbdata:
    driver: local
